### ISSUE TITLE
Must click twice to get correct mouse coordinates for canvas mouse:up event

### ISSUE THREAD

**Issue by johnbayne** [kangax/fabric.js#2561]
Video demonstration of issue here: http://screencast.com/t/Dd4sszkDqGg

I have a problem whereby I have to click the mouse on canvas twice in order to get an absolutely-positioned popup to display at the correct coordinates, triggered by canvas.on('mouse:up'). Upon clicking, the position of the popup should be set to: `{top: evt.pageX, left: evt.pageY}`, and while that happens on the second click, it is offset (usually down and right) of the actual coords. console.log evt.pageX shows the same coordinates on both the first (inaccurate) and second (accurate) click. I thought canvas.calcOffset() might be the problem, but it doesn't seem to provide any help. Any suggestions appreciated

Code here:

```coffee
class SheetTemplate
  CIRCLE_RADIUS: 8
  CIRCLE_BORDER: 2

  constructor: ->
    @canvas = new fabric.Canvas('sheet_template_image_path_canvas', {width: 800, height:600})
    @setElements()
    @setEvents()

  setElements: ->
    @image_path_el = $('#sheet_template_image_path')
    @popup_el = $('#sheet_template_popup')
    @popup_input_el = $('#sheet_template_popup_input')

  setEvents: ->
    @canvas.on('mouse:up', (evt) =>
      @showPopup(evt)
    )
    @popup_input_el.bind('keyup', (e) =>
      @submitLabel() if e.keyCode == 13
    )

  submitLabel: ->
    @popup_el.hide()
    @popup_input_el.val('')

  showPopup: (e) ->
    @popup_el.offset
      left: e.e.pageX
      top: e.e.pageY
    @popup_el.show()
$ ->
  @sheet_template = new SheetTemplate
```

```css
#sheet_template_popup {
  border: solid 1px #666;
  background: #fff;
  border-radius: 3px;
  position: absolute;
  display: none;
  input {
    width: 200px;
    height: 20px;
  }
}
```
